export default {
    ADD_DUMMY_USER: "ADD_DUMMY_USER",
    DELETE_SUBGROUP: "DELETE_SUBGROUP",
    FAILED_DUMMY_USER: "FAILED_DUMMY_USER",
    MARK_USER_FOR_DELETION: "MARK_USER_FOR_DELETION",
    RECEIVE_CONFIG: "RECEIVE_CONFIG",
    RECEIVE_GROUP_NAME: "RECEIVE_GROUP_NAME",
    RECEIVE_SUBGROUPS: "RECEIVE_SUBGROUPS",
    RECEIVE_USERS: "RECEIVE_USERS",
    REMOVE_USER: "REMOVE_USER",
    STORE_REGISTRATION_TOKEN: "STORE_REGISTRATION_TOKEN",
    UPDATE_USERS: "UPDATE_USERS",
    USER_AUTHENTICATION: "USER_AUTHENTICATION",
    RESET_STATE: "RESET_STATE",
    ADD_NOTIFICATION: "ADD_NOTIFICATION",
    REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
    TOGGLE_NETID_ALLOWED: "TOGGLE_NETID_ALLOWED"
}
