export const RECEIVE_GROUP_NAME = "RECEIVE_GROUP_NAME";
export const REQUEST_CONFIG = "REQUEST_CONFIG";
export const RECEIVE_CONFIG = "RECEIVE_CONFIG";
export const REQUEST_SUBGROUPS = "REQUEST_SUBGROUPS";
export const RECEIVE_SUBGROUPS = "RECEIVE_SUBGROUPS";
export const DELETE_SUBGROUP = "DELETE_SUBGROUP";
