export default {
    RECEIVE_GROUP_NAME: "RECEIVE_GROUP_NAME",
    RECEIVE_CONFIG: "RECEIVE_CONFIG",
    RECEIVE_SUBGROUPS: "RECEIVE_SUBGROUPS",
    DELETE_SUBGROUP: "DELETE_SUBGROUP",
    RECEIVE_USERS: "RECEIVE_USERS",
    UPDATE_USERS: "UPDATE_USERS",
    REMOVE_USER: "REMOVE_USER",
    USER_AUTHENTICATION: "USER_AUTHENTICATION",
    RECEIVE_AUTH: "RECEIVE_AUTH",
    ADD_DUMMY_USER: "ADD_DUMMY_USER",
    MARK_USER_FOR_DELETION: "MARK_USER_FOR_DELETION",
    STORE_REGISTRATION_TOKEN: "STORE_REGISTRATION_TOKEN"
}
